geekhub_task8:
    resource: "@GeekhubTask8Bundle/Resources/config/routing.yml"
    prefix:   /task8

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_welcome:
    pattern:   /
    defaults:  { _controller: MopaBootstrapSandboxBundle:Examples:index }
